version: '3.7'

services:
  web:
    build:
      context: .
    command: sh -c ./entrypoint.sh
    env_file:
      - .env.docker
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=552281
      - POSTGRES_DB=book_author
volumes:
  postgres_data: